# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

os:
  - linux
  - osx

r:
  - release
  - devel

jobs:
  exclude:
    - r: devel
      os: osx

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_PAT
  keep_history: true
  local_dir: docs
  on:
    branch: master
