#' Creates a plot showing all avaiable colors of the Aachen palette
#' @export
#'
#' @import ggplot2
#' @import stringr
#' @examples display_aachen_colors()
display_aachen_colors = function() {
  aachen_colors_df %>%
    dplyr::mutate(color = stringr::str_to_title(.data$color)) %>%
    dplyr::mutate(color = factor(.data$color, unique(.data$color)),
           intensity = factor(.data$intensity, unique(.data$intensity)),
           query = factor(.data$query, .data$query)) %>%
    ggplot2::ggplot(ggplot2::aes(x=.data$color, y=.data$intensity,
                                 color=.data$query)) +
    ggplot2::geom_point(size=9) +
    ggplot2::scale_color_manual(values = aachen_colors_df$hex) +
    ggplot2::theme_minimal() +
    ggplot2::theme(legend.position = "none",
                   axis.text = ggplot2::element_text(size=12),
                   title = ggplot2::element_text(size=14)) +
    ggplot2::coord_flip() +
    ggplot2::labs(x = "", y="Intensity [%]") +
    ggplot2::ggtitle("Aachen color palette")
}

#' Queries colors from Aachen color palette
#'
#' @param colors Query of colors. Query colors by combining color name in lower
#' case (check figure generated by
#' \code{\link[=display_aachen_colors]{display_aachen_colors()}} for
#' color names) and color intensity. For colors with 100\% intensity the color
#' name alone is sufficient.
#'
#' @return HEX code of queried colors
#' @export
#'
#' @importFrom dplyr anti_join inner_join pull
#' @importFrom tibble tibble
#'
#' @examples
#' aachen_color("maygreen")
#' aachen_color(c("blue", "blue75", "blue50", "blue25", "blue10"))
aachen_color = function(colors) {
  if (!all(colors %in% aachen_colors_df$query)) {
    wrong_queries = tibble::tibble(query = colors) %>%
      dplyr::anti_join(aachen_colors_df, by="query") %>%
      dplyr::pull(.data$query)
    warning(paste("The following queries are not available:",
                  paste(wrong_queries, collapse = ", ")))
  }
  tibble::tibble(query = colors) %>%
    dplyr::inner_join(aachen_colors_df, by="query") %>%
    dplyr::pull(.data$hex)
}
